name: davasus
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - tqdm
  - pandas
  - numpy
  - matplotlib
  - scipy
  - scikit-learn
  - openpyxl
  - pyyaml
  - rich
  - astral
  - pytest
  - pytest-cov
  - ruff
  - pip:
      - -e .
